[GLOBAL]
pants_version = "2.21.0"

backend_packages = [
    "pants.backend.python",
    "pants.backend.build_files.fmt.ruff",
    "pants.backend.experimental.python.lint.ruff.check",
    "pants.backend.experimental.python.lint.ruff.format",
]

[source]
root_patterns = ["src"]

[python]
interpreter_constraints = ["==3.12.*"]
enable_resolves = true

[python-infer]
# 2.17 is transitioning to a new, faster parser for dependency inference:
use_rust_parser = true
